### ISSUE TITLE
Consider renaming nodes to blocks

### ISSUE THREAD

**Issue by Raytar** [relab/hotstuff#10]
Since Gorums already uses the term `Node` to mean servers, we should consider renaming our node types to `Block` instead.

**Comment by meling** [comment]
Naming stuff is important. This also makes me thing about whether or not using `Node` to represent Gorums servers is a good thing. I don't want to make any changes to Gorums at this time, but it is certainly relevant to consider if also Gorums should use a different name than `Node`.

Two alternatives to `Block` could be `TreeNode` or `ChainNode`.
