### ISSUE TITLE
Communication complexity(performance) is O(n^2) rather than O(n) if quorum certificates are represented by arrays of ECDSA signatures

### ISSUE THREAD

**Issue by TinyVege** [relab/hotstuff#124]
![image](https://github.com/relab/hotstuff/assets/106942308/04b36497-3107-433c-b92a-af0a4ad22c65)

I notice that there are two implements cryptographic primitives(ecdsa, bls) used by HotStuff.
In my view, if using the ecdsa(eg. over secp256k1 in paper) signature,  quorum certificates can not be aggregated into only one signature right? So in the normal case, the communication complexity(performance) is is O(n^2) rather than O(n) right?

**Comment by meling** [comment]
It is true that ecdsa signatures cannot be aggregated into a single signature. However, I think you have misunderstood something else here. The ecdsa implementation requires $n$ signatures to represent a quorum certificate (QC). Hence, a message that carries a QC will carry $n$ signatures, not $n^2$ signatures. Thus, a QC based on ecdsa (or eddsa) will only impact the message size. Moreover, the communication complexity (the number of messages exchanged between the $n$ replicas) is not impacted by the type of signature, and is the same as for hotstuff.

Does this resolve your concern?

**Comment by TinyVege** [comment]
> The message complexity is O(n). It is true that ecdsa signatures cannot be aggregated into a single signature. The ecdsa implementation requires n signatures to represent a quorum certificate (QC). Hence, a message that carries a QC will carry n signatures, and will impact the message size. So yes, you are correct that the communication complexity is O(n2). This is inherent to the use of ecdsa or eddsa signature schemes. However, in terms of real-world performance, using ecdsa has lower latency and higher throughput than bls signatures for n<X where X∈[50,70] range; I don't recall the exact cross-over point. There was a paper at ApPLIED 2023 that studied this issue, but I think they used eddsa signatures.
> 
> (edited the message to correct my first response).

Thank you for your answer, it solved my confusion. 
By the way, what is the specific source of this study (ApPLIED 2023)
