### ISSUE TITLE
[Question]Where is vote method for replica

### ISSUE THREAD

**Issue by GrapeBaBa** [relab/hotstuff#14]
Hi guys,
After looked at the code, I only saw the self vote however I didn't see the code other replica send vote msg to next view leader `send(getLeader(), voteMsgu(generic, bnew , ⊥))` which refer to the paper. Am I missing anything?

**Comment by Raytar** [comment]
Hi,
we use the Gorums RPC framework for all of our communication between replicas. In our system, the RPC "client" is the leader replica. The leader executes the `Propose` RPC on all of the "servers", which are the rest of the replicas. The [server-side handler](https://github.com/relab/hotstuff/blob/3278a49fc2621564e8a32af4f340531f8a444ca0/gorumshotstuff/gorumshotstuff.go#L166) for the `Propose` RPC calls `OnReceiveProposal`, which returns the vote for that replica. The RPC framework then sends the vote back to the leader.

I hope that clears it up.

**Comment by GrapeBaBa** [comment]
@Raytar Thanks. As I read the paper, the voteMsg may not send back to proposal leader but a new leader instead, the getleader method can be vary in different pacemaker implementation. Does it make sense?

**Comment by Raytar** [comment]
Yes, that's correct. That is where our implementation differs from the paper. Our intent was to implement HotStuff using the *quorum call* abstraction that [Gorums](https://github.com/relab/gorums) provides. HotStuff's proposal process is compatible with the quorum call abstraction when the leader is constant, but not when the leader changes. Our current solution is that the old leader relays the qcHigh to the new leader through a NEW-VIEW message.

**Comment by GrapeBaBa** [comment]
@Raytar Thanks. I see it.
