### ISSUE TITLE
Incompatibility with new version of gonum

### ISSUE THREAD

**Issue by hangshao009** [relab/hotstuff#41]
### Discussed in https://github.com/relab/hotstuff/discussions/38

<div type='discussions-op-text'>

there are some question from the path :/mttrics/plotting/helper at line 20,Goland prompted that Assignment count mismatch: 2 = 1. I go into this method （plot.New()）and find that only one return value,but two var to accept.
![image](https://user-images.githubusercontent.com/40131866/159396320-e8c96df3-b849-4777-a244-cc7b59e380d8.png)

</div>

**Comment by hangshao009** [comment]
i find that is a version question,thx.

**Comment by Raytar** [comment]
Looks like you are using a newer package of the `gonum.org/v1/plot` package. We currently depend on `v0.8.1`, but I guess it shouldn't be too hard to update to the latest version.
