### ISSUE TITLE
Update go version and dependencies

### ISSUE THREAD

**Issue by meling** [relab/hotstuff#49]
The `go.mod` file contains the long-ago deprecated protobuf version:

```go
github.com/golang/protobuf v1.5.2
```

This dependency is used in `client` and `replica` packages. The fix is trivial; the import:

```go
"github.com/golang/protobuf/ptypes/empty"
```
should be replaced with:
```go
empty "google.golang.org/protobuf/types/known/emptypb"
```

Currently, we are using Go 1.16. I want to convert from slice to `[32]byte` array without using `copy`; this is supported in Go 1.17.

Finally, my installed `protoc-gen-gorums` is newer than the one used in the existing `pb.go` files, preventing me from generating compatible files. Hence, I propose to upgrade both the plugin and `relab/gorums` to latest release version. The necessary changes should be trivial. 

@Raytar @hanish520 Any reason to hold off from upgrading these dependencies?

**Comment by hanish520** [comment]
@meling, updating gorums to the latest version requires code changes in the parts that handle the configuration and unicast calls. I presume these changes are small. I don't see any issues with the plugin update.
