### ISSUE TITLE
How can I run this code among 4 machines in WAN environment?

### ISSUE THREAD

**Issue by hzxGoForward** [relab/hotstuff#52]
It seems that this code can only runs in a local machine, I am not sure that if there is a way to run this in a WAN environment.
I have 4 machines with global addresses, but I do not know how to run them in those machines.
Any one help me ?

**Comment by meling** [comment]
Closing due to age. Feel free to open another issue if this problem remains and there is a need to improve the docs on this. What you describe is definitely possible. Please feel free to contribute a PR with doc improvements if you figured it out.
