### ISSUE TITLE
Does anyone know how to use ./plot? Or how to output throughput and latency information

### ISSUE THREAD

**Issue by syysumuro** [relab/hotstuff#69]

**Comment by vvvn41** [comment]
######reference format
./plot -interval 2s -latency latency_plot.png -throughput throughput_plot.png -throughputvslatency combined_plot.png path/to/measurements.json_（the path of the measurements.json ）_
#####example
 sudo ./plot -throughputvslatency combined_plot.png measurements.json
###this is working  ，I hope it can help you

**Comment by meling** [comment]
Closing. We may consider improving the docs for `plot` in the future, meanwhile, you can run `./plot -help` to get help and read the code. I don't think you should ever run `sudo ./plot`.
