### ISSUE TITLE
Consider using the protobuf types for nodes and quorum certificates

### ISSUE THREAD

**Issue by Raytar** [relab/hotstuff#9]
Currently, we convert between our internal hotstuff node and quorum certificate structs and the protobuf message types. However, we should be able to improve performance and reduce memory allocations by using the protobuf types internally instead.

**Comment by meling** [comment]
This seems like a good first thing to do. It would be interesting to see the performance impact of this (both allocations and cpu cycles)

**Comment by Raytar** [comment]
Having done some CPU profiling, I have come to the conclusion that the potential performance gain by implementing this change is too small to consider right now (the convert to/from methods were responsible for less than 1% of CPU time). I don't think we can avoid all type conversions anyway.
