### ISSUE TITLE
Can someone resolve this error report："transport: Error while dialing dial tcp 127.0.0.1:36729: connect: connection refused

### ISSUE THREAD

**Issue by lyz19980208** [relab/hotstuff#94]
2023/03/17 10:40:28 failed to run experiment: failed to start replicas: rpc error: code = Unknown desc = failed to create configuration: could not create configuration: connection failed for addr: 127.0.0.1:36729: dialing node failed: context deadline exceeded: connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:36729: connect: connection refused"

**Comment by meling** [comment]
Closing due to age and not enough information to help debug the problem. Please file a new issue with more information if the issue is still relevant. We are quite busy though, so we can't promise to find time to help debug issues like this.
